# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:48:34+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class BasicUser(BaseModel):
    email: Optional[str] = Field(
        None,
        description='Email address of the user',
        examples=['john.smith@example.com'],
    )
    first_name: Optional[str] = Field(
        None, description='First name of the user', examples=['John']
    )
    last_name: Optional[str] = Field(
        None, description='Last name of the user', examples=['Smith']
    )
    login_name: Optional[str] = Field(
        None, description='Login name of the user', examples=['jsmith']
    )


class DID(BaseModel):
    custom_tag: Optional[str] = Field(
        None,
        description='Custom tag associated with the phone number',
        examples=['My Tag'],
    )
    phone_number: Optional[str] = Field(
        None, description='Phone number', examples=['14155550100']
    )


class DetailedInvalidParam(BaseModel):
    name: Optional[str] = Field(None, description='Invalid property name')
    reason: Optional[str] = Field(None, description='Invalid property reason')


class ErrorResponse(BaseModel):
    msg: Optional[str] = Field(None, description='Error message')
    status: Optional[float] = Field(None, description='Http Response Code')


class FirstHref(BaseModel):
    href: Optional[str] = None


class LastHref(BaseModel):
    href: Optional[str] = None


class Line(BaseModel):
    handset_name: Optional[str] = Field(
        None, description='Name of the handset', examples=['line1-VH6370927']
    )
    sip_id: Optional[str] = Field(
        None, description='SIP identifier of the handset', examples=['VH16370927']
    )


class NextHref(BaseModel):
    href: Optional[str] = None


class PrevHref(BaseModel):
    href: Optional[str] = None


class SelfHref(BaseModel):
    href: Optional[str] = None


class ValidationErrorsResponse(BaseModel):
    instance: Optional[str] = Field(None, description='Error Track ID')
    invalid_parameters: Optional[List[DetailedInvalidParam]] = Field(
        None, description='Invalid parameters and their reason for failing'
    )
    status: Optional[float] = Field(None, description='Error status code')
    title: Optional[str] = Field(None, description='Error title')


class EndUserRoute(BaseModel):
    block_caller_id: Optional[bool] = Field(
        None, description='Block Caller ID status of the extension', examples=[False]
    )
    caller_id: Optional[str] = Field(
        None, description='Caller ID of the extension', examples=['John Smith']
    )
    dids: Optional[List[DID]] = Field(
        None, description='Collection of phone numbers assigned to the extension'
    )
    dnd_enabled: Optional[bool] = Field(
        None, description='Do Not Disturb status of the extension', examples=[False]
    )
    extension_handsets: Optional[List[Line]] = Field(
        None, description='Collection of handsets assigned to the extension'
    )
    extension_number: Optional[str] = Field(
        None, description='Extension number', examples=['789']
    )
    location_id: Optional[float] = Field(
        None,
        description='Unique identifier of the assigned location',
        examples=[145214],
    )
    user: Optional[BasicUser] = None
    vtt_enabled: Optional[bool] = Field(
        None,
        description='Voicemail transcription status of the location',
        examples=[True],
    )


class EndUserRouteEmbeddedObject(BaseModel):
    data: Optional[EndUserRoute] = None


class Links(BaseModel):
    first: Optional[FirstHref] = None
    next: Optional[NextHref] = None
    prev: Optional[PrevHref] = None
    self: Optional[SelfHref] = None


class EndUserRouteHalResponse(BaseModel):
    field_embedded: Optional[EndUserRouteEmbeddedObject] = Field(
        None, alias='_embedded'
    )
    field_links: Optional[Links] = Field(None, alias='_links')
    page: Optional[float] = Field(None, description='Current page number', examples=[1])
    page_size: Optional[float] = Field(
        None, description='Number of records per page', examples=[10]
    )
    total_items: Optional[float] = Field(
        None, description='Total number of records', examples=[100]
    )
    total_pages: Optional[float] = Field(
        None, description='Total number of pages', examples=[10]
    )
